### ISSUE TITLE
How do you place blocks?

### ISSUE THREAD

**Issue by PythonCodeingKing** [Mineclone-Development-Team/Mineclone#1]
I'm on a mac with python 3.8. Any help you could give my would be awesome!
Thanks!

**Comment by Jatc252** [comment]
After having a look myself, it seems that on_mouse_press() wants 4 arguments, but Mineclone only gives it 3. I'll have a look into it later when I have a bit more time. You may be able to fix it by providing it with the extra argument it wants. If you get a working version, feel free to make a pull request with the changes.

**Comment by Jatc252** [comment]
Fixed now with v1.0.1

**Comment by PythonCodeingKing** [comment]
Thanks
